name = "hessenberg-paper"
defaultTargets = ["Paper", "generate-paper"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.28.0"

[[require]]
name = "HessenbergDigraphs"
path = "../../lean"

[[lean_lib]]
name = "Paper"

[[lean_exe]]
name = "generate-paper"
root = "Main"
