#!/usr/bin/env python3
r"""Bibliography lint (run from the vault root).

Every reference card carries a BibTeX entry and the label it is cited by.
Checks:
  1. every card has a `label:` and exactly one ```bibtex block
  2. the entry key is the label, lowercased — one name, not two
  3. labels are unique: two works cannot cite as [CM05]
  4. author and year are present; the year agrees with the label's digits
  5. bibliography/references.bib is in sync with the cards
Exit code 1 if any check fails. Usage: python3 tools/bib_lint.py
"""
import pathlib, re, sys, collections

V = pathlib.Path(__file__).resolve().parent.parent
DIR = V / 'bibliography' / 'references'
BIB = V / 'bibliography' / 'references.bib'

bad, entries, labels = [], [], collections.defaultdict(list)

for f in sorted(DIR.glob('ref-*.md')):
    text = f.read_text()
    fm = text.split('---', 2)[1] if text.startswith('---') else ''
    label = (re.search(r'^label:\s*(\S+)', fm, re.M) or [None, None])[1]
    blocks = re.findall(r'```bibtex\n(.*?)\n```', text, re.S)

    if not label:
        bad.append((f, 'no label:')); continue
    if len(blocks) != 1:
        bad.append((f, f'{len(blocks)} bibtex blocks, expected 1')); continue

    entry = blocks[0]
    entries.append(entry)
    labels[label].append(f.stem)

    key = (re.search(r'^@\w+\{([^,]+),', entry) or [None, None])[1]
    if key != label.lower():
        bad.append((f, f'key {key!r} is not the label {label.lower()!r}'))
    for field in ('author', 'title', 'year'):
        if not re.search(rf'^\s*{field}\s*=', entry, re.M):
            bad.append((f, f'entry has no {field}'))
    year = (re.search(r'^\s*year\s*=\s*\{(\d{4})\}', entry, re.M) or [None, None])[1]
    digits = re.search(r'(\d{2})[a-z]?$', label)
    if year and digits and year[-2:] != digits.group(1):
        bad.append((f, f'label {label} disagrees with year {year}'))

for label, stems in sorted(labels.items()):
    if len(stems) > 1:
        bad.append((DIR, f'label [{label}] claimed by {", ".join(stems)}'))

want = ('% Generated by tools/gen_bib.py from bibliography/references/*.md — do not edit.\n'
        '% The card is the source of truth; this file is for LaTeX.\n\n'
        + '\n\n'.join(entries) + '\n')
if not BIB.exists():
    bad.append((BIB, 'missing — run tools/gen_bib.py'))
elif BIB.read_text() != want:
    bad.append((BIB, 'out of sync with the cards — run tools/gen_bib.py'))

if bad:
    for f, msg in bad[:40]:
        print(f'{f.relative_to(V)}: {msg}')
    print(f'\n{len(bad)} offender(s).')
    sys.exit(1)
print(f'bib lint: clean ({len(entries)} entries)')
