#!/usr/bin/env python3
r"""frontier.py — what to expand next in the curated pools.

Reports, and writes to FRONTIER.md (kept out of the graph view):
  1. proof debts    — clean-pool atoms (non-definitions) without a Proof;
  2. graduation frontier — targets cited in clean-pool Statements/Proofs
     that still live in the raw pool (hard dependencies, ordered by how
     many clean cards cite them);
  3. notes-only pointers — pool targets cited only in Notes or the
     `references:` frontmatter (soft).

Run any time; regenerates FRONTIER.md.
"""
import re, pathlib, collections
import sys as _sys; _sys.path.insert(0, str(__import__("pathlib").Path(__file__).parent)); import pools

V = pathlib.Path(__file__).resolve().parent.parent

pool_stems = {f.stem for f in pools.files(pools.RAW)}
clean_stems = {f.stem for f in pools.atoms()}

LINK = re.compile(r'\[\[([^\]|#]+)')
debts, opens, hard, soft = [], [], collections.defaultdict(set), collections.defaultdict(set)

for f in pools.atoms():
    t = f.read_text()
    typ = (re.search(r'^type: (\w+)', t, re.M) or [None, '?'])[1]
    m = re.search(r'## Statement\n(.*?)(?=\n## Notes|\n## References|\Z)', t, re.S)
    body = m.group(1) if m else ''
    notes = t[m.end():] if m else ''
    fm = re.match(r'\A---\n(.*?)\n---\n', t, re.S)
    if fm:                       # references: frontmatter counts as soft pointers
        notes += '\n' + fm.group(1)
    # A card can be settled without a prose proof, if a formal one stands in its
    # place: every `lean:` entry resolved and `state: proven`. That is `formal`
    # rather than `proved`, because the two are read differently — `proved` says
    # a reader can follow the argument here, `formal` says a machine has checked
    # it elsewhere and the card is pointing at it.
    lean_block = re.search(r'^lean:\n((?:  - .*\n(?:    .*\n)*)+)', t, re.M)
    states = re.findall(r'^    state: (\S+)', lean_block.group(1), re.M) if lean_block else []
    formal = bool(states) and all(s == 'proven' for s in states)

    # A third way to be settled without a prose proof here: the statement is a
    # known theorem this network consumes and does not reprove, with the place
    # it is proved named in `cited:`. That is not a debt — nothing is missing —
    # but it is not `proved` either, because a reader cannot follow it here.
    # Keeping the two apart is the difference between "this argument rests on
    # nothing unstated" and "this argument rests on nothing at all", and only
    # the first is ever true.
    cited = bool(re.search(r'^cited:', t, re.M))

    # A conjecture is exempt for a different reason than a definition or a
    # remark. Those have nothing to prove; a conjecture has nothing *this
    # network* owes — it is named, not relied on. Left in, every conjecture
    # card would be reported as a proof debt, which reads as "the argument
    # rests on an assumption" and is exactly wrong.
    if typ not in ('definition', 'remark', 'conjecture', 'equation'):
        if '## Proof' not in t:
            want = 'formal' if formal else ('cited' if cited else 'debt')
        elif any(x.strip() in pool_stems for x in LINK.findall(body)):
            want = 'open'
        else:
            want = 'proved'
        cur = re.search(r'^status: (\w+)', t, re.M)
        if not cur or cur.group(1) != want:
            if cur:
                t2 = re.sub(r'^status: \w+', 'status: ' + want, t, count=1, flags=re.M)
            else:
                t2 = re.sub(r'^(id: \w+\n)', r'\1status: ' + want + '\n', t, count=1, flags=re.M)
            f.write_text(t2)
            t = t2
        if want == 'debt':
            debts.append(f.stem)
        elif want == 'open':
            opens.append(f.stem)
    for target in LINK.findall(body):
        if target.strip() in pool_stems:
            hard[target.strip()].add(f.stem)
    for target in LINK.findall(notes):
        s = target.strip()
        if s in pool_stems and s not in hard:
            soft[s].add(f.stem)

# ---- aggregate state ----
from collections import Counter
types = Counter(); statuses = Counter()
for af in pools.atoms():
    at = af.read_text()
    typ = (re.search(r'^type: (\w+)', at, re.M) or [None, '?'])[1]
    types[typ] += 1
    st = re.search(r'^status: (\w+)', at, re.M)
    if st: statuses[st.group(1)] += 1
n_edges = sum(1 for _ in pools.edges())
n_pool_grad = sum(1 for pf in pools.files(pools.RAW) if 'graduated:' in pf.read_text())
prov = statuses.get('proved', 0); opn = statuses.get('open', 0); dbt = statuses.get('debt', 0)
fml = statuses.get('formal', 0); ctd = statuses.get('cited', 0)
tot = prov + fml + ctd + opn + dbt
out = ['What to expand next. Generated by `tools/frontier.py`; do not edit.', '',
 '## State of the graph', '',
 f"- **{sum(types.values())} atoms** ("
   + ', '.join(f"{v} {k.replace('ary','arie')}s" for k, v in sorted(types.items(), key=lambda kv: -kv[1])) + ')'
   + f' · **{n_edges} edges**' + (f' · {n_pool_grad} pool cards graduated' if pools.RAW else ''),
 f"- statements needing proof work: **{prov} proved · {fml} formal · {ctd} cited · {opn} open · {dbt} debt**"
   + (f'  (settled {prov + fml + ctd}/{tot})' if tot else ''),
 '',
 '**How to read**: *debt* (red on the canvas) = statement stands, proof missing;',
       '*cited* = a known theorem consumed here and proved in the literature, named in `cited:`;',
       '*formal* = no prose proof, but a machine-checked one is named in `lean:`;',
 ('*open* (magenta) = proved, but the proof still cites raw-pool cards;' if pools.RAW else ''),
 '*proved* = self-contained in this pool. The layers at the bottom are the',
 'order in which a Lean skeleton would be written: a layer needs only earlier ones.', '',
       '## Proof debts (statement graduated, proof missing)', '']
out += [f'- [[{s}]]' for s in debts] or ['- (none)']
# The next three sections are about a raw pool. This vault declares none, so
# they are always empty here and printing them makes the report describe a
# structure that is not there. The code stays — it is the same file the vaults
# with a pool run — and only the empty sections are suppressed.
if pools.RAW:
    out += ['', '## Open cards (proved, but the proof still reaches into the pool)', '']
    out += [f'- [[{s}]]' for s in opens] or ['- (none)']
    out += ['', '## Graduation frontier (cited in a Statement/Proof, still in the pool)', '']
    for tgt, srcs in sorted(hard.items(), key=lambda kv: -len(kv[1])):
        out.append(f'- [[{tgt}]] ← cited by {", ".join(sorted(srcs))}')
    if not hard: out.append('- (none)')
    out += ['', '## Notes-only pool pointers (soft)', '']
    for tgt, srcs in sorted(soft.items()):
        out.append(f'- [[{tgt}]] ← {", ".join(sorted(srcs))}')
    if not soft: out.append('- (none)')

# ---- formalization order: topological sort over clean-pool edges ----
cedges = []   # (src, tgt) among clean atoms
for ef in pools.edges():
    et = ef.read_text()
    refs = re.findall(r'"\[\[([^\]]+)\]\]"', et)
    if len(refs) == 2 and refs[0] in clean_stems and refs[1] in clean_stems:
        cedges.append((refs[0], refs[1]))
deps = {s: set() for s in clean_stems}
for s, tgt in cedges:
    deps[s].add(tgt)
layers, placed = [], set()
while len(placed) < len(deps):
    layer = sorted(s for s, d in deps.items() if s not in placed and d <= placed)
    if not layer:
        cyc = sorted(s for s in deps if s not in placed)
        out += ['', '## ⚠ Cycle detected', ''] + [f'- [[{s}]]' for s in cyc]
        print('CYCLE among:', ', '.join(cyc))
        break
    layers.append(layer); placed |= set(layer)
out += ['', '## Formalization order (leaves first; a layer needs only earlier layers)', '']
for i, layer in enumerate(layers):
    out.append(f'{i+1}. ' + ' · '.join(f'[[{s}]]' for s in layer))
(V / 'FRONTIER.md').write_text('\n'.join(out) + '\n')
print(f'cited: {statuses.get("cited", 0)}  |  proof debts: {len(debts)}  |  open: {len(opens)}  |  hard frontier: {len(hard)}  |  soft: {len(soft)}')
for s in debts: print('  debt :', s)
for s in opens: print('  open :', s)
for tgt, srcs in sorted(hard.items(), key=lambda kv: -len(kv[1])):
    print(f'  next : {tgt}  (x{len(srcs)})')
