#!/usr/bin/env python3
r"""Concatenate the cards' BibTeX entries into paper/references.bib.

The card is the source of truth — one work, one Markdown file, like every
other node here. This file exists so LaTeX can \bibliography it.
Usage: python3 tools/gen_bib.py
"""
import pathlib, re

V = pathlib.Path(__file__).resolve().parent.parent
entries = []
for f in sorted((V / 'bibliography' / 'references').glob('ref-*.md')):
    m = re.search(r'```bibtex\n(.*?)\n```', f.read_text(), re.S)
    if m:
        entries.append(m.group(1))
out = V / 'paper' / 'references.bib'

# The paper's bib is what LaTeX reads, so refuse to shrink it. Until every
# work cited by the paper has a card, generating would drop the rest.
old = len(re.findall(r'^@', out.read_text(), re.M)) if out.exists() else 0
if len(entries) < old:
    raise SystemExit(f'refusing to overwrite {out.relative_to(V)}: '
                     f'{old} entries there, only {len(entries)} cards to write')

out.write_text('% Generated by tools/gen_bib.py from bibliography/references/*.md — do not edit.\n'
               '% The card is the source of truth; this file is for LaTeX.\n\n'
               + '\n\n'.join(entries) + '\n')
print(f'wrote {out.relative_to(V)}: {len(entries)} entries')
